### ISSUE TITLE
Torchserve does not use GPU, Jetson Nano

### ISSUE THREAD

**Issue by kaangoksal** [pytorch/serve#1289]
## Context

Can't use torchserve on jetson platforms, by default it uses cpu for inference which results in slow inference. 

```
(venv2) ubuntu@jetson-nano-1:~/Desktop$ pip3 list
Package                 Version
----------------------- ---------------------
absl-py                 0.15.0
cachetools              4.2.4
captum                  0.4.0
certifi                 2021.10.8
charset-normalizer      2.0.7
cycler                  0.10.0
dataclasses             0.8
enum-compat             0.0.3
future                  0.18.2
google-auth             2.3.0
google-auth-oauthlib    0.4.6
grpcio                  1.41.0
idna                    3.3
importlib-metadata      4.8.1
kiwisolver              1.3.1
Markdown                3.3.4
matplotlib              3.3.4
numpy                   1.19.5
oauthlib                3.1.1
onnx                    1.10.1
opencv-python           4.5.4.58
packaging               21.0
pandas                  1.1.5
Pillow                  8.3.2
pip                     21.3.1
pkg_resources           0.0.0
protobuf                3.19.0
psutil                  5.8.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pyparsing               3.0.0
python-dateutil         2.8.2
pytz                    2021.3
PyYAML                  6.0
requests                2.26.0
requests-oauthlib       1.3.0
rsa                     4.7.2
scipy                   1.5.4
seaborn                 0.11.2
sentencepiece           0.1.96
setuptools              58.3.0
six                     1.16.0
tensorboard             2.7.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.0
thop                    0.0.31.post2005241907
torch                   1.7.0
torch-model-archiver    0.4.2
torchserve              0.4.2
torchvision             0.8.2+2f40a48
tqdm                    4.62.3
typing-extensions       3.10.0.2
urllib3                 1.26.7
Werkzeug                2.0.2
wheel                   0.37.0
zipp                    3.6.0
```
* Operating System and version: Ubuntu 18 running on Jetson Nano, 

Cuda version 

```
(venv2) ubuntu@jetson-nano-1:~/Desktop/yolov5$ cat /usr/local/cuda/version.txt 
CUDA Version 10.2.300

```

## Your Environment

* Installed using source? [yes/no]:
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: custom handler: 

```
"""Custom TorchServe model handler for YOLOv5 models.
"""
from ts.torch_handler.base_handler import BaseHandler
import numpy as np
import base64
import torch
import torchvision.transforms as tf
import torchvision
import io
from PIL import Image


class ModelHandler(BaseHandler):
    """
    A custom model handler implementation.
    """

    img_size = 640
    """Image size (px). Images will be resized to this resolution before inference.
    """

    def __init__(self):
        # call superclass initializer
        super().__init__()

    def preprocess(self, data):
        """Converts input images to float tensors.
        Args:
            data (List): Input data from the request in the form of a list of image tensors.
        Returns:
            Tensor: single Tensor of shape [BATCH_SIZE, 3, IMG_SIZE, IMG_SIZE]
        """
        images = []

        transform = tf.Compose([
            tf.ToTensor(),
            tf.Resize((self.img_size, self.img_size))
        ])

        # load images
        # taken from https://github.com/pytorch/serve/blob/master/ts/torch_handler/vision_handler.py

        # handle if images are given in base64, etc.
        for row in data:
            # Compat layer: normally the envelope should just return the data
            # directly, but older versions of Torchserve didn't have envelope.
            image = row.get("data") or row.get("body")
            if isinstance(image, str):
                # if the image is a string of bytesarray.
                image = base64.b64decode(image)

            # If the image is sent as bytesarray
            if isinstance(image, (bytearray, bytes)):
                image = Image.open(io.BytesIO(image))
            else:
                # if the image is a list
                image = torch.FloatTensor(image)

            # force convert to tensor
            # and resize to [img_size, img_size]
            image = transform(image)

            images.append(image)

        # convert list of equal-size tensors to single stacked tensor
        # has shape BATCH_SIZE x 3 x IMG_SIZE x IMG_SIZE
        images_tensor = torch.stack(images).to(self.device)

        return images_tensor

    def postprocess(self, inference_output):
        # perform NMS (nonmax suppression) on model outputs
        pred = non_max_suppression(inference_output[0])

        # initialize empty list of detections for each image
        detections = [[] for _ in range(len(pred))]

        for i, image_detections in enumerate(pred):  # axis 0: for each image
            for det in image_detections:  # axis 1: for each detection
                # x1,y1,x2,y2 in normalized image coordinates (i.e. 0.0-1.0)
                xyxy = det[:4] / self.img_size
                # confidence value
                conf = det[4].item()
                # index of predicted class
                class_idx = int(det[5].item())
                # get label of predicted class
                # if missing, then just return class idx
                label = self.mapping.get(str(class_idx), class_idx)

                detections[i].append({
                    "x1": xyxy[0].item(),
                    "y1": xyxy[1].item(),
                    "x2": xyxy[2].item(),
                    "y2": xyxy[3].item(),
                    "confidence": conf,
                    "class": label
                })

        # format each detection
        return detections


def non_max_suppression(prediction, conf_thres=0.25, iou_thres=0.45, classes=None, agnostic=False, multi_label=False,
                        labels=(), max_det=300):
    """Runs Non-Maximum Suppression (NMS) on inference results
    Returns:
         list of detections, on (n,6) tensor per image [xyxy, conf, cls]
    """

    nc = prediction.shape[2] - 5  # number of classes
    xc = prediction[..., 4] > conf_thres  # candidates

    # Checks
    assert 0 <= conf_thres <= 1, f'Invalid Confidence threshold {conf_thres}, valid values are between 0.0 and 1.0'
    assert 0 <= iou_thres <= 1, f'Invalid IoU {iou_thres}, valid values are between 0.0 and 1.0'

    # Settings
    # (pixels) minimum and maximum box width and height
    min_wh, max_wh = 2, 4096
    max_nms = 30000  # maximum number of boxes into torchvision.ops.nms()
    time_limit = 10.0  # seconds to quit after
    redundant = True  # require redundant detections
    multi_label &= nc > 1  # multiple labels per box (adds 0.5ms/img)
    merge = False  # use merge-NMS

    output = [torch.zeros((0, 6), device=prediction.device)
              ] * prediction.shape[0]
    for xi, x in enumerate(prediction):  # image index, image inference
        # Apply constraints
        # x[((x[..., 2:4] < min_wh) | (x[..., 2:4] > max_wh)).any(1), 4] = 0  # width-height
        x = x[xc[xi]]  # confidence

        # Cat apriori labels if autolabelling
        if labels and len(labels[xi]):
            l = labels[xi]
            v = torch.zeros((len(l), nc + 5), device=x.device)
            v[:, :4] = l[:, 1:5]  # box
            v[:, 4] = 1.0  # conf
            v[range(len(l)), l[:, 0].long() + 5] = 1.0  # cls
            x = torch.cat((x, v), 0)

        # If none remain process next image
        if not x.shape[0]:
            continue

        # Compute conf
        x[:, 5:] *= x[:, 4:5]  # conf = obj_conf * cls_conf

        # Box (center x, center y, width, height) to (x1, y1, x2, y2)
        box = xywh2xyxy(x[:, :4])

        # Detections matrix nx6 (xyxy, conf, cls)
        if multi_label:
            i, j = (x[:, 5:] > conf_thres).nonzero(as_tuple=False).T
            x = torch.cat((box[i], x[i, j + 5, None], j[:, None].float()), 1)
        else:  # best class only
            conf, j = x[:, 5:].max(1, keepdim=True)
            x = torch.cat((box, conf, j.float()), 1)[
                conf.view(-1) > conf_thres]

        # Filter by class
        if classes is not None:
            x = x[(x[:, 5:6] == torch.tensor(classes, device=x.device)).any(1)]

        # Apply finite constraint
        # if not torch.isfinite(x).all():
        #     x = x[torch.isfinite(x).all(1)]

        # Check shape
        n = x.shape[0]  # number of boxes
        if not n:  # no boxes
            continue
        elif n > max_nms:  # excess boxes
            # sort by confidence
            x = x[x[:, 4].argsort(descending=True)[:max_nms]]

        # Batched NMS
        c = x[:, 5:6] * (0 if agnostic else max_wh)  # classes
        # boxes (offset by class), scores
        boxes, scores = x[:, :4] + c, x[:, 4]
        i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
        if i.shape[0] > max_det:  # limit detections
            i = i[:max_det]
        if merge and (1 < n < 3E3):  # Merge NMS (boxes merged using weighted mean)
            # update boxes as boxes(i,4) = weights(i,n) * boxes(n,4)
            iou = torchvision.box_iou(
                boxes[i], boxes) > iou_thres  # iou matrix
            weights = iou * scores[None]  # box weights
            x[i, :4] = torch.mm(weights, x[:, :4]).float(
            ) / weights.sum(1, keepdim=True)  # merged boxes
            if redundant:
                i = i[iou.sum(1) > 1]  # require redundancy

        output[xi] = x[i]

    return output


def xywh2xyxy(x):
    # Convert nx4 boxes from [x, y, w, h] to [x1, y1, x2, y2] where xy1=top-left, xy2=bottom-right
    y = x.clone() if isinstance(x, torch.Tensor) else np.copy(x)
    y[:, 0] = x[:, 0] - x[:, 2] / 2  # top left x
    y[:, 1] = x[:, 1] - x[:, 3] / 2  # top left y
    y[:, 2] = x[:, 0] + x[:, 2] / 2  # bottom right x
    y[:, 3] = x[:, 1] + x[:, 3] / 2  # bottom right y
    return y

```
* What kind of model is it e.g. vision, text, audio?: Vision, using the model weights from [here](https://github.com/ultralytics/yolov5) 

* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]: (cleaning it up right now will release it soon)

## Expected Behavior

torchserve must use GPU,

## Current Behavior
torch serve is not using gpu: 
```
curl http://localhost:8081/models/yolov5s

[
  {
    "modelName": "yolov5s",
    "modelVersion": "0.1",
    "modelUrl": "yolov5s.mar",
    "runtime": "python",
    "minWorkers": 4,
    "maxWorkers": 4,
    "batchSize": 1,
    "maxBatchDelay": 100,
    "loadedAtStartup": true,
    "workers": [
      {
        "id": "9000",
        "startTime": "2021-10-23T17:00:19.028Z",
        "status": "READY",
        "memoryUsage": 0,
        "pid": -1,
        "gpu": false,
        "gpuUsage": "N/A"
      },
      {
        "id": "9001",
        "startTime": "2021-10-23T17:00:19.222Z",
        "status": "READY",
        "memoryUsage": 0,
        "pid": -1,
        "gpu": false,
        "gpuUsage": "N/A"
      },
      {
        "id": "9002",
        "startTime": "2021-10-23T17:00:19.223Z",
        "status": "READY",
        "memoryUsage": 0,
        "pid": -1,
        "gpu": false,
        "gpuUsage": "N/A"
      },
      {
        "id": "9003",
        "startTime": "2021-10-23T17:00:19.224Z",
        "status": "READY",
        "memoryUsage": 0,
        "pid": -1,
        "gpu": false,
        "gpuUsage": "N/A"
      }
    ]
  }
]
```

even though my installed pytorch says cuda is available: 

```
(venv2) ubuntu@jetson-nano-1:~/Desktop$ python
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
im>>> import torch

>>> 
>>> torch.cuda.is_available()
True
>>> torch.__version__
'1.7.0'
>>> import torchvision
>>> torchvision.__version__
'0.8.2+2f40a48'
>>> 

```
I launch torch serve as following: 

```

MODEL_LIST="yolov5s=yolov5s.mar"
torchserve --start --model-store work_dir --models ${MODEL_LIST}  --foreground --no-config-snapshots

```

## Possible Solution

I read people saying there are CPU/GPU models. Maybe my models are packed for cpu and I need to pack them for GPU?

**Comment by kaangoksal** [comment]
Here is the code that I'm using. (https://gitlab.com/kaangoksal/yolov5_torchserve/-/blob/master/torchserve_handler_yolov5.py) 

You can find other files there as well, thats the whole project.
This is the log output on jetson nano for inference, as you can see, torch library says cuda is there! 


```
2021-10-29 11:33:40,219 [INFO ] W-9001-yolov5s_0.1-stdout MODEL_LOG - Torch version: 1.7.0
2021-10-29 11:33:40,219 [INFO ] W-9001-yolov5s_0.1-stdout MODEL_LOG - Torch Cuda Available: True



2021-10-29 11:33:40,220 [INFO ] W-9001-yolov5s_0.1-stdout MODEL_METRICS - HandlerTime.Milliseconds:2900.76|#ModelName:yolov5s,Level:Model|#hostname:jetson-nano-1,requestID:cce37dc7-ea52-4fe0-aba4-b3ffcde43370,timestamp:1635532420
2021-10-29 11:33:40,221 [INFO ] W-9001-yolov5s_0.1 org.pytorch.serve.wlm.WorkerThread - Backend response time: 2904
2021-10-29 11:33:40,222 [INFO ] W-9001-yolov5s_0.1-stdout MODEL_METRICS - PredictionTime.Milliseconds:2900.91|#ModelName:yolov5s,Level:Model|#hostname:jetson-nano-1,requestID:cce37dc7-ea52-4fe0-aba4-b3ffcde43370,timestamp:1635532420
2021-10-29 11:33:40,226 [INFO ] W-9001-yolov5s_0.1 ACCESS_LOG - /127.0.0.1:46654 "PUT /predictions/yolov5s HTTP/1.1" 200 2937

```

although something interesting, the initial statements that list system specs says there is no gpu available (Number of GPUs: 0):

```
(venv2) ubuntu@jetson-nano-1:~/Desktop/yolov5$ ./scripts/serve.sh 
Removing orphan pid file.
2021-10-29 11:32:38,965 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2021-10-29 11:32:39,363 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.4.2
TS Home: /home/ubuntu/Desktop/venv2/lib/python3.6/site-packages
Current directory: /home/ubuntu/Desktop/yolov5
Temp directory: /tmp
Number of GPUs: 0
Number of CPUs: 4
Max heap size: 992 M
Python executable: /home/ubuntu/Desktop/venv2/bin/python3
Config file: ts.config
Inference address: http://0.0.0.0:8080
Management address: http://127.0.0.1:8081
Metrics address: http://127.0.0.1:8082
Model Store: /home/ubuntu/Desktop/yolov5/work_dir
Initial Models: yolov5s=yolov5s.mar
Log dir: /home/ubuntu/Desktop/yolov5/logs
Metrics dir: /home/ubuntu/Desktop/yolov5/logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 4
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: false
Metrics report format: prometheus
Enable metrics API: true
Workflow Store: /home/ubuntu/Desktop/yolov5/work_dir
Model config: N/A

```

I downloaded a docker image from nvidia for jetson, I will play with that as well, maybe there is an environment variable or something I need to set. 


per your recommendation, I also tried passing ts.config file to force gpus. (https://gitlab.com/kaangoksal/yolov5_torchserve/-/blob/master/ts.config)

It didn't make a difference.

**Comment by kaangoksal** [comment]
okay, I'm finding leads here, jetson nano does not have nvidia-smi (https://forums.developer.nvidia.com/t/gpu-usage-info-nvidia-smi-is-not-there/76155)

 torchserve uses 
 
 `Process process =Runtime.getRuntime().exec("nvidia-smi --query-gpu=index --format=csv");` 
 
 to find whether there are gpus available! 

 https://github.com/pytorch/serve/blob/7b1c6007cce0b4ed2caa2c20851b547b8827bee9/frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java#L722
  
  
 worst case I will make a fake nvidia-smi script that spits out what this thing expects for jetson nano

**Comment by kaangoksal** [comment]
I found the problem and I believe I solved it, I'm seeing gpu utilization with `tegrastats` also my inference time is instant. 

Here is what I did
0) You need to find the correct combination of pytorch & torchvision that will work with jetson. Here are the links  

(Pytorch for jetson)[https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-10-now-available/72048]
(torchvision version compability)[https://pytorch.org/get-started/previous-versions/]  

I will document and automate these on my project.   

1) torchserve uses `nvidia-smi` to find out how many gpus you have, nvidia tegra boards (Jetson TX2, Jetson Nano) don't have that tool, so you need to fake the tool.   

```bash
#!/bin/bash
echo index
echo 0
```
save this as `nvidia-smi` in a folder, chmod it `chmod 700 nvidia-smi` and add it to your path as following  

`export PATH="/home/ubuntu/Desktop/yolov5/jetson-files:$PATH"`   

this command will only work for the current session, for persistence add it to bashrc (google is your friend)  

2) make sure that the base handler detects GPU, add print statements and other stuff to see what device is selected etc.  

3) It might take a minute for the model to boot up, after 2-3 requests my inference became instant.  

I will document more of my findings in this project!
https://gitlab.com/kaangoksal/yolov5_torchserve
